# Generated by Django 4.1.7 on 2023-03-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='publish',
        ),
    ]
